apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resource-capacity
spec:
  version: {{ .TagName }}
  homepage: https://github.com/robscott/kube-capacity
  shortDescription: Provides an overview of resource requests, limits, and utilization
  description: |
    A simple CLI that provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/{{ .TagName }}/kube-capacity_{{ .TagName }}_darwin_x86_64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/{{ .TagName }}/kube-capacity_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/{{ .TagName }}/kube-capacity_{{ .TagName }}_linux_x86_64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    bin: kube-capacity
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/{{ .TagName }}/kube-capacity_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    bin: kube-capacity.exe
    files:
    - from: "*"
      to: "."
    {{addURIAndSha "https://github.com/robscott/kube-capacity/releases/download/{{ .TagName }}/kube-capacity_{{ .TagName }}_windows_x86_64.zip" .TagName }}
